apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # 1. Infrastructure (Applied directly by kubectl or the bootstrap app)
  - sys-traefik/traefik-config.yaml
  - sys-argocd/ingress-route.yaml

  # 2. The Application Generator (The AppSet)
  - appset.yaml