tempo:
  repository: grafana/tempo
  tag: 2.9.0
  storage:
    trace:
      backend: s3
      s3:
        bucket: tempo-traces
        endpoint:  'http://swfs-s3.data.svc:8333'
        insecure: true
        secret_key: "$(SWFS_S3_SECRET_KEY)"
        access_key: "$(SWFS_S3_ACCESS_KEY)"
  # Critical: Disable the "distributed" microservices defaults
  distributor:
    enabled: false
  ingester:
    enabled: false
  compactor:
    enabled: false
  querier:
    enabled: false
  queryFrontend:
    enabled: false

# Enable the "Monolithic" Mode
fullnameOverride: tempo
gateway:
  enabled: false # We will send data directly

extraEnvFrom:
  - secretRef:
      name: monitoring-creds